[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[profile.default.optimizer]
enabled = true
runs = 200

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/config
